packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - '@cloudflare/workerd-darwin-64@1.20260916.1'
  - '@cloudflare/workerd-darwin-arm64@1.20260916.1'
  - '@cloudflare/workerd-linux-64@1.20260916.1'
  - '@cloudflare/workerd-linux-arm64@1.20260916.1'
  - '@cloudflare/workerd-windows-64@1.20260916.1'
  - '@cloudflare/workers-types@5.20260916.1'
  - miniflare@5.20260916.0-alpha
  - workerd@1.20260916.1
  - wrangler@4.133.0
